---
downloads: ~/.ansible-downloads

homebrew_installed_packages:
  - please

homebrew_taps:
  - thought-machine/please

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - visual-studio-code
