---
downloads: ~/.ansible-downloads

homebrew_installed_packages:
  - pulumi

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - visual-studio-code
